// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IndirectX.TypeGenerator.Templates
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class InterfaceTemplate : InterfaceTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// <auto-generated>\r\n// THIS CODE FILE IS GENERATED BY IndirectX.TypeGenerator.\r\n" +
                    "// DO NOT CHANGE IT.\r\n// </auto-generated>\r\n#nullable enable\r\n");
 foreach(var import in Setting.ImportNamespaces) { 
            this.Write("using ");
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            this.Write(";\r\n");
 } 
            this.Write("using System.Runtime.InteropServices;\r\nusing System.Runtime.CompilerServices;\r\nus" +
                    "ing ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Setting.Namespace));
            this.Write(".Interop;\r\n\r\nnamespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Setting.Namespace));
            this.Write("\r\n{\r\n    [Guid(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Guid));
            this.Write("\")]\r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Modifier));
            this.Write(" unsafe partial class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            this.Write(" : ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ParentName));
            this.Write("\r\n\t{\r\n        private ref readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            this.Write("Vtbl VtblRef\r\n        {\r\n            [MethodImpl(MethodImplOptions.AggressiveInli" +
                    "ning)]\r\n            get => ref Unsafe.AsRef<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            this.Write("Vtbl>(*(void**)ComPtr.Native);\r\n        }\r\n\r\n\t    public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            this.Write("(ComPtr nativePtr, bool addRef = false) : base(nativePtr, addRef) { }\r\n");
    foreach (var method in Model.Methods)
	  { 
     if (method.Delete) 
     { 
            this.Write("        // Deleted method ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.SourceName));
            this.Write("\r\n");
     } 
     else 
     { 
            this.Write("\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Modifier));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ManagedReturnType));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ParameterText));
            this.Write(")\r\n        {\r\n");
        foreach (var ps in method.Prestatements)
          { 
            this.Write("            ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ps));
            this.Write("\r\n");
        } 
        foreach (var bs in method.BlockStatements)
          { 
            this.Write("            ");
            this.Write(this.ToStringHelper.ToStringWithCulture(bs));
            this.Write("\r\n");
        } 
            this.Write("            {\r\n                ");
 if (method.ReturnNative) { 
            this.Write("return ");
 } 
            this.Write("VtblRef.");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write("(ComPtr");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ArgText));
            this.Write(")");
 
			if (!method.ReturnNative && method.NativeReturnType == "HResult") { 
            this.Write(".HandleResult()");
 } 
            this.Write(";\r\n");
          if (!method.ReturnNative && method.Outputs.Count() > 0)
            { 
            this.Write("\t\t\t    return (");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ReturnText));
            this.Write(");\r\n");
          } 
            this.Write("            }\r\n        }\r\n");
      if (method.Parameters.Any(p => p.IsOptional))
        { 
            this.Write("\r\n        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Modifier));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ManagedReturnType));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.OptionalParameterText));
            this.Write(")\r\n        {\r\n");
        foreach (var ps in method.OptionalPrestatements)
          { 
            this.Write("            ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ps));
            this.Write("\r\n");
        } 
        foreach (var bs in method.OptionalBlockStatements)
          { 
            this.Write("            ");
            this.Write(this.ToStringHelper.ToStringWithCulture(bs));
            this.Write("\r\n");
        } 
            this.Write("            {\r\n                ");
 if (method.ReturnNative) { 
            this.Write("return ");
 } 
            this.Write("VtblRef.");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write("(ComPtr");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.OptionalArgText));
            this.Write(")");
 
			if (!method.ReturnNative && method.NativeReturnType == "HResult") { 
            this.Write(".HandleResult()");
 } 
            this.Write(";\r\n");
          if (!method.ReturnNative && method.Outputs.Count() > 0)
            { 
            this.Write("\t\t\t    return (");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.ReturnText));
            this.Write(");\r\n");
          } 
            this.Write("            }\r\n        }\r\n");
      } 
     } 
    }
      foreach (var (name, type, hasSetter) in Model.Properties)
      { 
        if (hasSetter)
        { 
            this.Write("\r\n        public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(type));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            this.Write("\r\n        {\r\n            get => Get");
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            this.Write("();\r\n            set => Set");
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            this.Write("(value);\r\n        }\r\n");
      }
        else 
        { 
            this.Write("\r\n        public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(type));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            this.Write(" => Get");
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            this.Write("();\r\n");
      } 
    } 
            this.Write("\t}\r\n}\r\n\r\nnamespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Setting.Namespace));
            this.Write(".Interop\r\n{\r\n    [StructLayout(LayoutKind.Sequential)]\r\n\t");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Modifier));
            this.Write(" unsafe struct ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            this.Write("Vtbl\r\n\t{\r\n\t    internal ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ParentName));
            this.Write("Vtbl Base;\r\n");
    foreach (var method in Model.Methods)
      { 
            this.Write("        internal delegate* unmanaged[Stdcall]<ComPtr, ");

		  foreach (var p in method.Parameters)
		  {
			
            this.Write(this.ToStringHelper.ToStringWithCulture(p.NativeType));
            this.Write(", ");

	      } 
            this.Write(this.ToStringHelper.ToStringWithCulture(method.NativeReturnType));
            this.Write("> ");
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            this.Write(";\r\n");
    } 
            this.Write("\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class InterfaceTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
