// <auto-generated>
// THIS CODE FILE IS GENERATED BY IndirectX.TypeGenerator.
// DO NOT CHANGE IT.
// </auto-generated>
#nullable enable
using System;
using IndirectX.Interop;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using IndirectX.D3DCompiler.Interop;

namespace IndirectX.D3DCompiler
{
    [Guid("8ba5fb08-5195-40e2-ac58-0d989c3a0102")]
    public unsafe partial class Blob : Unknown
	{
        private ref readonly BlobVtbl VtblRef
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => ref Unsafe.AsRef<BlobVtbl>(*(void**)ComPtr.Native);
        }

	    public Blob(ComPtr nativePtr, bool addRef = false) : base(nativePtr, addRef) { }

        public void* GetBufferPointer()
        {
            return VtblRef.GetBufferPointer(ComPtr);
        }

        public nint GetBufferSize()
        {
            return VtblRef.GetBufferSize(ComPtr);
        }

        public void* BufferPointer => GetBufferPointer();

        public nint BufferSize => GetBufferSize();

        public Span<byte> AsSpan() => new Span<byte>(BufferPointer, (int)BufferSize);

        public static implicit operator Span<byte>(Blob blob) => new Span<byte>(blob.BufferPointer, (int)blob.BufferSize);
    }
}

namespace IndirectX.D3DCompiler.Interop
{
    [StructLayout(LayoutKind.Sequential)]
	public unsafe struct BlobVtbl
	{
	    public UnknownVtbl Base;
        public delegate* unmanaged[Stdcall]<ComPtr, void*> GetBufferPointer;
        public delegate* unmanaged[Stdcall]<ComPtr, nint> GetBufferSize;
	}
}
